Repository ArcadyRob/polar-dash, pull requests merged in 2023-10, with the labels that each got.

#28 added a line to readme file on building project and added two lines t…
  .gitignore
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#33 Feature/design system
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/app/styles/main.scss
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#34 added storybook
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#37 adds simple countdown timer
  src/app/page.tsx
  src/components/Timer/Timer.tsx
  src/components/Timer/index.ts
  src/components/Timer/useTimer.tsx
  src/components/index.ts
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#39 Feat/loading spinner
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  postcss.config.js
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/app/styles/main.scss
  src/assets/svg/polar-bear-head.svg
  src/components/Spinner/BearSpinner.stories.tsx
  src/components/Spinner/BearSpinner.tsx
  src/components/Spinner/index.ts
  src/components/index.ts
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#40 feat: added trivia questions
  src/questions/TriviaQuestions.csv
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#36 High score marquee
  .gitignore
  .idea/.gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/polar-dash.iml
  .idea/vcs.xml
  components/highscore.tsx
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/app/styles/main.scss
  src/components/Highscore/Highscore.scss
  src/components/Highscore/Highscore.tsx
  tsconfig.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
